/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.solicitudes_sdisc.model.model.Delegado;
import la.netco.solicitudes_sdisc.model.model.DelegadoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Delegado service. Represents a row in the &quot;SOLISALAD_DELEGADO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.solicitudes_sdisc.model.model.DelegadoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DelegadoImpl}.
 * </p>
 *
 * @author smontanez
 * @see DelegadoImpl
 * @see la.netco.solicitudes_sdisc.model.model.Delegado
 * @see la.netco.solicitudes_sdisc.model.model.DelegadoModel
 * @generated
 */
public class DelegadoModelImpl extends BaseModelImpl<Delegado>
	implements DelegadoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a delegado model instance should use the {@link la.netco.solicitudes_sdisc.model.model.Delegado} interface instead.
	 */
	public static final String TABLE_NAME = "SOLISALAD_DELEGADO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_delegado", Types.INTEGER },
			{ "nombre", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SOLISALAD_DELEGADO (id_delegado INTEGER not null primary key IDENTITY,nombre VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SOLISALAD_DELEGADO";
	public static final String ORDER_BY_JPQL = " ORDER BY delegado.nombre ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SOLISALAD_DELEGADO.nombre ASC";
	public static final String DATA_SOURCE = "csjDBDatasource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.solicitudes_sdisc.model.model.Delegado"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.solicitudes_sdisc.model.model.Delegado"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.solicitudes_sdisc.model.model.Delegado"));

	public DelegadoModelImpl() {
	}

	public int getPrimaryKey() {
		return _id_delegado;
	}

	public void setPrimaryKey(int primaryKey) {
		setId_delegado(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id_delegado);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return Delegado.class;
	}

	public String getModelClassName() {
		return Delegado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_delegado", getId_delegado());
		attributes.put("nombre", getNombre());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id_delegado = (Integer)attributes.get("id_delegado");

		if (id_delegado != null) {
			setId_delegado(id_delegado);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}
	}

	public int getId_delegado() {
		return _id_delegado;
	}

	public void setId_delegado(int id_delegado) {
		_id_delegado = id_delegado;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	@Override
	public Delegado toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Delegado)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DelegadoImpl delegadoImpl = new DelegadoImpl();

		delegadoImpl.setId_delegado(getId_delegado());
		delegadoImpl.setNombre(getNombre());

		delegadoImpl.resetOriginalValues();

		return delegadoImpl;
	}

	public int compareTo(Delegado delegado) {
		int value = 0;

		value = getNombre().compareTo(delegado.getNombre());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Delegado delegado = null;

		try {
			delegado = (Delegado)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = delegado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Delegado> toCacheModel() {
		DelegadoCacheModel delegadoCacheModel = new DelegadoCacheModel();

		delegadoCacheModel.id_delegado = getId_delegado();

		delegadoCacheModel.nombre = getNombre();

		String nombre = delegadoCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			delegadoCacheModel.nombre = null;
		}

		return delegadoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_delegado=");
		sb.append(getId_delegado());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("la.netco.solicitudes_sdisc.model.model.Delegado");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_delegado</column-name><column-value><![CDATA[");
		sb.append(getId_delegado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Delegado.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Delegado.class
		};
	private int _id_delegado;
	private String _nombre;
	private Delegado _escapedModelProxy;
}