/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.solicitudes_sdisc.model.model.Especialidad;
import la.netco.solicitudes_sdisc.model.model.EspecialidadModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Especialidad service. Represents a row in the &quot;T062BAESPEGENE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.solicitudes_sdisc.model.model.EspecialidadModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EspecialidadImpl}.
 * </p>
 *
 * @author smontanez
 * @see EspecialidadImpl
 * @see la.netco.solicitudes_sdisc.model.model.Especialidad
 * @see la.netco.solicitudes_sdisc.model.model.EspecialidadModel
 * @generated
 */
public class EspecialidadModelImpl extends BaseModelImpl<Especialidad>
	implements EspecialidadModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a especialidad model instance should use the {@link la.netco.solicitudes_sdisc.model.model.Especialidad} interface instead.
	 */
	public static final String TABLE_NAME = "T062BAESPEGENE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "A062CODIESPE", Types.VARCHAR },
			{ "A062DESCESPE", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table T062BAESPEGENE (A062CODIESPE VARCHAR(75) not null primary key,A062DESCESPE VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table T062BAESPEGENE";
	public static final String DATA_SOURCE = "csjDBDatasourceEntidades";
	public static final String SESSION_FACTORY = "entSessionFactory";
	public static final String TX_MANAGER = "entTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.solicitudes_sdisc.model.model.Especialidad"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.solicitudes_sdisc.model.model.Especialidad"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.solicitudes_sdisc.model.model.Especialidad"));

	public EspecialidadModelImpl() {
	}

	public String getPrimaryKey() {
		return _codigo;
	}

	public void setPrimaryKey(String primaryKey) {
		setCodigo(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return _codigo;
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	public Class<?> getModelClass() {
		return Especialidad.class;
	}

	public String getModelClassName() {
		return Especialidad.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("codigo", getCodigo());
		attributes.put("nombre", getNombre());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String codigo = (String)attributes.get("codigo");

		if (codigo != null) {
			setCodigo(codigo);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}
	}

	public String getCodigo() {
		if (_codigo == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigo;
		}
	}

	public void setCodigo(String codigo) {
		_codigo = codigo;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	@Override
	public Especialidad toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Especialidad)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		EspecialidadImpl especialidadImpl = new EspecialidadImpl();

		especialidadImpl.setCodigo(getCodigo());
		especialidadImpl.setNombre(getNombre());

		especialidadImpl.resetOriginalValues();

		return especialidadImpl;
	}

	public int compareTo(Especialidad especialidad) {
		String primaryKey = especialidad.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Especialidad especialidad = null;

		try {
			especialidad = (Especialidad)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		String primaryKey = especialidad.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Especialidad> toCacheModel() {
		EspecialidadCacheModel especialidadCacheModel = new EspecialidadCacheModel();

		especialidadCacheModel.codigo = getCodigo();

		String codigo = especialidadCacheModel.codigo;

		if ((codigo != null) && (codigo.length() == 0)) {
			especialidadCacheModel.codigo = null;
		}

		especialidadCacheModel.nombre = getNombre();

		String nombre = especialidadCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			especialidadCacheModel.nombre = null;
		}

		return especialidadCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{codigo=");
		sb.append(getCodigo());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("la.netco.solicitudes_sdisc.model.model.Especialidad");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>codigo</column-name><column-value><![CDATA[");
		sb.append(getCodigo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Especialidad.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Especialidad.class
		};
	private String _codigo;
	private String _nombre;
	private Especialidad _escapedModelProxy;
}