/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.solicitudes_sdisc.model.model.Estado;
import la.netco.solicitudes_sdisc.model.model.EstadoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Estado service. Represents a row in the &quot;SOLISALAD_ESTADO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.solicitudes_sdisc.model.model.EstadoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EstadoImpl}.
 * </p>
 *
 * @author smontanez
 * @see EstadoImpl
 * @see la.netco.solicitudes_sdisc.model.model.Estado
 * @see la.netco.solicitudes_sdisc.model.model.EstadoModel
 * @generated
 */
public class EstadoModelImpl extends BaseModelImpl<Estado>
	implements EstadoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a estado model instance should use the {@link la.netco.solicitudes_sdisc.model.model.Estado} interface instead.
	 */
	public static final String TABLE_NAME = "SOLISALAD_ESTADO";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_estado", Types.INTEGER },
			{ "nombre", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SOLISALAD_ESTADO (id_estado INTEGER not null primary key IDENTITY,nombre VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SOLISALAD_ESTADO";
	public static final String ORDER_BY_JPQL = " ORDER BY estado.nombre ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SOLISALAD_ESTADO.nombre ASC";
	public static final String DATA_SOURCE = "csjDBDatasource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.solicitudes_sdisc.model.model.Estado"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.solicitudes_sdisc.model.model.Estado"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.la.netco.solicitudes_sdisc.model.model.Estado"),
			true);
	public static long NOMBRE_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.solicitudes_sdisc.model.model.Estado"));

	public EstadoModelImpl() {
	}

	public int getPrimaryKey() {
		return _id_estado;
	}

	public void setPrimaryKey(int primaryKey) {
		setId_estado(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id_estado);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return Estado.class;
	}

	public String getModelClassName() {
		return Estado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_estado", getId_estado());
		attributes.put("nombre", getNombre());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id_estado = (Integer)attributes.get("id_estado");

		if (id_estado != null) {
			setId_estado(id_estado);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}
	}

	public int getId_estado() {
		return _id_estado;
	}

	public void setId_estado(int id_estado) {
		_id_estado = id_estado;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_columnBitmask = -1L;

		if (_originalNombre == null) {
			_originalNombre = _nombre;
		}

		_nombre = nombre;
	}

	public String getOriginalNombre() {
		return GetterUtil.getString(_originalNombre);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Estado toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Estado)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		EstadoImpl estadoImpl = new EstadoImpl();

		estadoImpl.setId_estado(getId_estado());
		estadoImpl.setNombre(getNombre());

		estadoImpl.resetOriginalValues();

		return estadoImpl;
	}

	public int compareTo(Estado estado) {
		int value = 0;

		value = getNombre().compareTo(estado.getNombre());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Estado estado = null;

		try {
			estado = (Estado)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = estado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		EstadoModelImpl estadoModelImpl = this;

		estadoModelImpl._originalNombre = estadoModelImpl._nombre;

		estadoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Estado> toCacheModel() {
		EstadoCacheModel estadoCacheModel = new EstadoCacheModel();

		estadoCacheModel.id_estado = getId_estado();

		estadoCacheModel.nombre = getNombre();

		String nombre = estadoCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			estadoCacheModel.nombre = null;
		}

		return estadoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_estado=");
		sb.append(getId_estado());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("la.netco.solicitudes_sdisc.model.model.Estado");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_estado</column-name><column-value><![CDATA[");
		sb.append(getId_estado());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Estado.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Estado.class
		};
	private int _id_estado;
	private String _nombre;
	private String _originalNombre;
	private long _columnBitmask;
	private Estado _escapedModelProxy;
}