/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import la.netco.solicitudes_sdisc.model.model.Parametros;
import la.netco.solicitudes_sdisc.model.service.ParametrosLocalServiceUtil;

/**
 * The extended model base implementation for the Parametros service. Represents a row in the &quot;SOLISALAD_PARAMETROS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParametrosImpl}.
 * </p>
 *
 * @author smontanez
 * @see ParametrosImpl
 * @see la.netco.solicitudes_sdisc.model.model.Parametros
 * @generated
 */
public abstract class ParametrosBaseImpl extends ParametrosModelImpl
	implements Parametros {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parametros model instance should use the {@link Parametros} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			ParametrosLocalServiceUtil.addParametros(this);
		}
		else {
			ParametrosLocalServiceUtil.updateParametros(this);
		}
	}
}