/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.solicitudes_sdisc.model.model.Parametros;
import la.netco.solicitudes_sdisc.model.model.ParametrosModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Parametros service. Represents a row in the &quot;SOLISALAD_PARAMETROS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.solicitudes_sdisc.model.model.ParametrosModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParametrosImpl}.
 * </p>
 *
 * @author smontanez
 * @see ParametrosImpl
 * @see la.netco.solicitudes_sdisc.model.model.Parametros
 * @see la.netco.solicitudes_sdisc.model.model.ParametrosModel
 * @generated
 */
public class ParametrosModelImpl extends BaseModelImpl<Parametros>
	implements ParametrosModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parametros model instance should use the {@link la.netco.solicitudes_sdisc.model.model.Parametros} interface instead.
	 */
	public static final String TABLE_NAME = "SOLISALAD_PARAMETROS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "tiempo_proximo_caducar", Types.INTEGER },
			{ "tiempo_caducidad", Types.INTEGER },
			{ "email_resposable", Types.VARCHAR },
			{ "mensaje_email", Types.VARCHAR },
			{ "asunto_email", Types.VARCHAR },
			{ "id_", Types.INTEGER },
			{ "repositoryId", Types.BIGINT },
			{ "folderId", Types.BIGINT },
			{ "userRepositoryId", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table SOLISALAD_PARAMETROS (tiempo_proximo_caducar INTEGER,tiempo_caducidad INTEGER,email_resposable VARCHAR(75) null,mensaje_email VARCHAR(75) null,asunto_email VARCHAR(75) null,id_ INTEGER not null primary key IDENTITY,repositoryId LONG,folderId LONG,userRepositoryId LONG)";
	public static final String TABLE_SQL_DROP = "drop table SOLISALAD_PARAMETROS";
	public static final String DATA_SOURCE = "csjDBDatasource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.solicitudes_sdisc.model.model.Parametros"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.solicitudes_sdisc.model.model.Parametros"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.solicitudes_sdisc.model.model.Parametros"));

	public ParametrosModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return Parametros.class;
	}

	public String getModelClassName() {
		return Parametros.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("tiempo_proximo_caducar", getTiempo_proximo_caducar());
		attributes.put("tiempo_caducidad", getTiempo_caducidad());
		attributes.put("email_resposable", getEmail_resposable());
		attributes.put("mensaje_email", getMensaje_email());
		attributes.put("asunto_email", getAsunto_email());
		attributes.put("id", getId());
		attributes.put("repositoryId", getRepositoryId());
		attributes.put("folderId", getFolderId());
		attributes.put("userRepositoryId", getUserRepositoryId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer tiempo_proximo_caducar = (Integer)attributes.get(
				"tiempo_proximo_caducar");

		if (tiempo_proximo_caducar != null) {
			setTiempo_proximo_caducar(tiempo_proximo_caducar);
		}

		Integer tiempo_caducidad = (Integer)attributes.get("tiempo_caducidad");

		if (tiempo_caducidad != null) {
			setTiempo_caducidad(tiempo_caducidad);
		}

		String email_resposable = (String)attributes.get("email_resposable");

		if (email_resposable != null) {
			setEmail_resposable(email_resposable);
		}

		String mensaje_email = (String)attributes.get("mensaje_email");

		if (mensaje_email != null) {
			setMensaje_email(mensaje_email);
		}

		String asunto_email = (String)attributes.get("asunto_email");

		if (asunto_email != null) {
			setAsunto_email(asunto_email);
		}

		Integer id = (Integer)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long repositoryId = (Long)attributes.get("repositoryId");

		if (repositoryId != null) {
			setRepositoryId(repositoryId);
		}

		Long folderId = (Long)attributes.get("folderId");

		if (folderId != null) {
			setFolderId(folderId);
		}

		Long userRepositoryId = (Long)attributes.get("userRepositoryId");

		if (userRepositoryId != null) {
			setUserRepositoryId(userRepositoryId);
		}
	}

	public int getTiempo_proximo_caducar() {
		return _tiempo_proximo_caducar;
	}

	public void setTiempo_proximo_caducar(int tiempo_proximo_caducar) {
		_tiempo_proximo_caducar = tiempo_proximo_caducar;
	}

	public int getTiempo_caducidad() {
		return _tiempo_caducidad;
	}

	public void setTiempo_caducidad(int tiempo_caducidad) {
		_tiempo_caducidad = tiempo_caducidad;
	}

	public String getEmail_resposable() {
		if (_email_resposable == null) {
			return StringPool.BLANK;
		}
		else {
			return _email_resposable;
		}
	}

	public void setEmail_resposable(String email_resposable) {
		_email_resposable = email_resposable;
	}

	public String getMensaje_email() {
		if (_mensaje_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _mensaje_email;
		}
	}

	public void setMensaje_email(String mensaje_email) {
		_mensaje_email = mensaje_email;
	}

	public String getAsunto_email() {
		if (_asunto_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _asunto_email;
		}
	}

	public void setAsunto_email(String asunto_email) {
		_asunto_email = asunto_email;
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_id = id;
	}

	public long getRepositoryId() {
		return _repositoryId;
	}

	public void setRepositoryId(long repositoryId) {
		_repositoryId = repositoryId;
	}

	public long getFolderId() {
		return _folderId;
	}

	public void setFolderId(long folderId) {
		_folderId = folderId;
	}

	public long getUserRepositoryId() {
		return _userRepositoryId;
	}

	public void setUserRepositoryId(long userRepositoryId) {
		_userRepositoryId = userRepositoryId;
	}

	@Override
	public Parametros toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Parametros)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		ParametrosImpl parametrosImpl = new ParametrosImpl();

		parametrosImpl.setTiempo_proximo_caducar(getTiempo_proximo_caducar());
		parametrosImpl.setTiempo_caducidad(getTiempo_caducidad());
		parametrosImpl.setEmail_resposable(getEmail_resposable());
		parametrosImpl.setMensaje_email(getMensaje_email());
		parametrosImpl.setAsunto_email(getAsunto_email());
		parametrosImpl.setId(getId());
		parametrosImpl.setRepositoryId(getRepositoryId());
		parametrosImpl.setFolderId(getFolderId());
		parametrosImpl.setUserRepositoryId(getUserRepositoryId());

		parametrosImpl.resetOriginalValues();

		return parametrosImpl;
	}

	public int compareTo(Parametros parametros) {
		int primaryKey = parametros.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Parametros parametros = null;

		try {
			parametros = (Parametros)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = parametros.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Parametros> toCacheModel() {
		ParametrosCacheModel parametrosCacheModel = new ParametrosCacheModel();

		parametrosCacheModel.tiempo_proximo_caducar = getTiempo_proximo_caducar();

		parametrosCacheModel.tiempo_caducidad = getTiempo_caducidad();

		parametrosCacheModel.email_resposable = getEmail_resposable();

		String email_resposable = parametrosCacheModel.email_resposable;

		if ((email_resposable != null) && (email_resposable.length() == 0)) {
			parametrosCacheModel.email_resposable = null;
		}

		parametrosCacheModel.mensaje_email = getMensaje_email();

		String mensaje_email = parametrosCacheModel.mensaje_email;

		if ((mensaje_email != null) && (mensaje_email.length() == 0)) {
			parametrosCacheModel.mensaje_email = null;
		}

		parametrosCacheModel.asunto_email = getAsunto_email();

		String asunto_email = parametrosCacheModel.asunto_email;

		if ((asunto_email != null) && (asunto_email.length() == 0)) {
			parametrosCacheModel.asunto_email = null;
		}

		parametrosCacheModel.id = getId();

		parametrosCacheModel.repositoryId = getRepositoryId();

		parametrosCacheModel.folderId = getFolderId();

		parametrosCacheModel.userRepositoryId = getUserRepositoryId();

		return parametrosCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{tiempo_proximo_caducar=");
		sb.append(getTiempo_proximo_caducar());
		sb.append(", tiempo_caducidad=");
		sb.append(getTiempo_caducidad());
		sb.append(", email_resposable=");
		sb.append(getEmail_resposable());
		sb.append(", mensaje_email=");
		sb.append(getMensaje_email());
		sb.append(", asunto_email=");
		sb.append(getAsunto_email());
		sb.append(", id=");
		sb.append(getId());
		sb.append(", repositoryId=");
		sb.append(getRepositoryId());
		sb.append(", folderId=");
		sb.append(getFolderId());
		sb.append(", userRepositoryId=");
		sb.append(getUserRepositoryId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("la.netco.solicitudes_sdisc.model.model.Parametros");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>tiempo_proximo_caducar</column-name><column-value><![CDATA[");
		sb.append(getTiempo_proximo_caducar());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tiempo_caducidad</column-name><column-value><![CDATA[");
		sb.append(getTiempo_caducidad());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email_resposable</column-name><column-value><![CDATA[");
		sb.append(getEmail_resposable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mensaje_email</column-name><column-value><![CDATA[");
		sb.append(getMensaje_email());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>asunto_email</column-name><column-value><![CDATA[");
		sb.append(getAsunto_email());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>repositoryId</column-name><column-value><![CDATA[");
		sb.append(getRepositoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>folderId</column-name><column-value><![CDATA[");
		sb.append(getFolderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userRepositoryId</column-name><column-value><![CDATA[");
		sb.append(getUserRepositoryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Parametros.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Parametros.class
		};
	private int _tiempo_proximo_caducar;
	private int _tiempo_caducidad;
	private String _email_resposable;
	private String _mensaje_email;
	private String _asunto_email;
	private int _id;
	private long _repositoryId;
	private long _folderId;
	private long _userRepositoryId;
	private Parametros _escapedModelProxy;
}