/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import la.netco.solicitudes_sdisc.model.model.PerfilImplicado;
import la.netco.solicitudes_sdisc.model.model.PerfilImplicadoModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PerfilImplicado service. Represents a row in the &quot;SOLISALAD_PERFIL_IMPL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link la.netco.solicitudes_sdisc.model.model.PerfilImplicadoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PerfilImplicadoImpl}.
 * </p>
 *
 * @author smontanez
 * @see PerfilImplicadoImpl
 * @see la.netco.solicitudes_sdisc.model.model.PerfilImplicado
 * @see la.netco.solicitudes_sdisc.model.model.PerfilImplicadoModel
 * @generated
 */
public class PerfilImplicadoModelImpl extends BaseModelImpl<PerfilImplicado>
	implements PerfilImplicadoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a perfil implicado model instance should use the {@link la.netco.solicitudes_sdisc.model.model.PerfilImplicado} interface instead.
	 */
	public static final String TABLE_NAME = "SOLISALAD_PERFIL_IMPL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_perfil", Types.INTEGER },
			{ "nombre", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table SOLISALAD_PERFIL_IMPL (id_perfil INTEGER not null primary key IDENTITY,nombre VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SOLISALAD_PERFIL_IMPL";
	public static final String DATA_SOURCE = "csjDBDatasource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.la.netco.solicitudes_sdisc.model.model.PerfilImplicado"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.la.netco.solicitudes_sdisc.model.model.PerfilImplicado"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.la.netco.solicitudes_sdisc.model.model.PerfilImplicado"));

	public PerfilImplicadoModelImpl() {
	}

	public int getPrimaryKey() {
		return _id_perfil;
	}

	public void setPrimaryKey(int primaryKey) {
		setId_perfil(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id_perfil);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return PerfilImplicado.class;
	}

	public String getModelClassName() {
		return PerfilImplicado.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_perfil", getId_perfil());
		attributes.put("nombre", getNombre());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer id_perfil = (Integer)attributes.get("id_perfil");

		if (id_perfil != null) {
			setId_perfil(id_perfil);
		}

		String nombre = (String)attributes.get("nombre");

		if (nombre != null) {
			setNombre(nombre);
		}
	}

	public int getId_perfil() {
		return _id_perfil;
	}

	public void setId_perfil(int id_perfil) {
		_id_perfil = id_perfil;
	}

	public String getNombre() {
		if (_nombre == null) {
			return StringPool.BLANK;
		}
		else {
			return _nombre;
		}
	}

	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	@Override
	public PerfilImplicado toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (PerfilImplicado)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		PerfilImplicadoImpl perfilImplicadoImpl = new PerfilImplicadoImpl();

		perfilImplicadoImpl.setId_perfil(getId_perfil());
		perfilImplicadoImpl.setNombre(getNombre());

		perfilImplicadoImpl.resetOriginalValues();

		return perfilImplicadoImpl;
	}

	public int compareTo(PerfilImplicado perfilImplicado) {
		int primaryKey = perfilImplicado.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		PerfilImplicado perfilImplicado = null;

		try {
			perfilImplicado = (PerfilImplicado)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = perfilImplicado.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PerfilImplicado> toCacheModel() {
		PerfilImplicadoCacheModel perfilImplicadoCacheModel = new PerfilImplicadoCacheModel();

		perfilImplicadoCacheModel.id_perfil = getId_perfil();

		perfilImplicadoCacheModel.nombre = getNombre();

		String nombre = perfilImplicadoCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			perfilImplicadoCacheModel.nombre = null;
		}

		return perfilImplicadoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_perfil=");
		sb.append(getId_perfil());
		sb.append(", nombre=");
		sb.append(getNombre());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("la.netco.solicitudes_sdisc.model.model.PerfilImplicado");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_perfil</column-name><column-value><![CDATA[");
		sb.append(getId_perfil());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombre</column-name><column-value><![CDATA[");
		sb.append(getNombre());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PerfilImplicado.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			PerfilImplicado.class
		};
	private int _id_perfil;
	private String _nombre;
	private PerfilImplicado _escapedModelProxy;
}