/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Especialidad service. Represents a row in the &quot;T062BAESPEGENE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.EspecialidadModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.EspecialidadImpl}.
 * </p>
 *
 * @author smontanez
 * @see Especialidad
 * @see la.netco.solicitudes_sdisc.model.model.impl.EspecialidadImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.EspecialidadModelImpl
 * @generated
 */
public interface EspecialidadModel extends BaseModel<Especialidad> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a especialidad model instance should use the {@link Especialidad} interface instead.
	 */

	/**
	 * Returns the primary key of this especialidad.
	 *
	 * @return the primary key of this especialidad
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this especialidad.
	 *
	 * @param primaryKey the primary key of this especialidad
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codigo of this especialidad.
	 *
	 * @return the codigo of this especialidad
	 */
	@AutoEscape
	public String getCodigo();

	/**
	 * Sets the codigo of this especialidad.
	 *
	 * @param codigo the codigo of this especialidad
	 */
	public void setCodigo(String codigo);

	/**
	 * Returns the nombre of this especialidad.
	 *
	 * @return the nombre of this especialidad
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this especialidad.
	 *
	 * @param nombre the nombre of this especialidad
	 */
	public void setNombre(String nombre);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Especialidad especialidad);

	public int hashCode();

	public CacheModel<Especialidad> toCacheModel();

	public Especialidad toEscapedModel();

	public String toString();

	public String toXmlString();
}