/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FechaNoHabil service. Represents a row in the &quot;SOLISALAD_FECHA_NO_HABIL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.FechaNoHabilModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.FechaNoHabilImpl}.
 * </p>
 *
 * @author smontanez
 * @see FechaNoHabil
 * @see la.netco.solicitudes_sdisc.model.model.impl.FechaNoHabilImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.FechaNoHabilModelImpl
 * @generated
 */
public interface FechaNoHabilModel extends BaseModel<FechaNoHabil> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fecha no habil model instance should use the {@link FechaNoHabil} interface instead.
	 */

	/**
	 * Returns the primary key of this fecha no habil.
	 *
	 * @return the primary key of this fecha no habil
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this fecha no habil.
	 *
	 * @param primaryKey the primary key of this fecha no habil
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this fecha no habil.
	 *
	 * @return the ID of this fecha no habil
	 */
	public int getId();

	/**
	 * Sets the ID of this fecha no habil.
	 *
	 * @param id the ID of this fecha no habil
	 */
	public void setId(int id);

	/**
	 * Returns the fecha of this fecha no habil.
	 *
	 * @return the fecha of this fecha no habil
	 */
	public Date getFecha();

	/**
	 * Sets the fecha of this fecha no habil.
	 *
	 * @param fecha the fecha of this fecha no habil
	 */
	public void setFecha(Date fecha);

	/**
	 * Returns the nombre of this fecha no habil.
	 *
	 * @return the nombre of this fecha no habil
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this fecha no habil.
	 *
	 * @param nombre the nombre of this fecha no habil
	 */
	public void setNombre(String nombre);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FechaNoHabil fechaNoHabil);

	public int hashCode();

	public CacheModel<FechaNoHabil> toCacheModel();

	public FechaNoHabil toEscapedModel();

	public String toString();

	public String toXmlString();
}