/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Implicado service. Represents a row in the &quot;SOLISALAD_IMPLICADO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.ImplicadoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.ImplicadoImpl}.
 * </p>
 *
 * @author smontanez
 * @see Implicado
 * @see la.netco.solicitudes_sdisc.model.model.impl.ImplicadoImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.ImplicadoModelImpl
 * @generated
 */
public interface ImplicadoModel extends BaseModel<Implicado> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a implicado model instance should use the {@link Implicado} interface instead.
	 */

	/**
	 * Returns the primary key of this implicado.
	 *
	 * @return the primary key of this implicado
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this implicado.
	 *
	 * @param primaryKey the primary key of this implicado
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id_implicado of this implicado.
	 *
	 * @return the id_implicado of this implicado
	 */
	public int getId_implicado();

	/**
	 * Sets the id_implicado of this implicado.
	 *
	 * @param id_implicado the id_implicado of this implicado
	 */
	public void setId_implicado(int id_implicado);

	/**
	 * Returns the nombre of this implicado.
	 *
	 * @return the nombre of this implicado
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this implicado.
	 *
	 * @param nombre the nombre of this implicado
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the despacho_entidad of this implicado.
	 *
	 * @return the despacho_entidad of this implicado
	 */
	@AutoEscape
	public String getDespacho_entidad();

	/**
	 * Sets the despacho_entidad of this implicado.
	 *
	 * @param despacho_entidad the despacho_entidad of this implicado
	 */
	public void setDespacho_entidad(String despacho_entidad);

	/**
	 * Returns the id_perfil of this implicado.
	 *
	 * @return the id_perfil of this implicado
	 */
	public int getId_perfil();

	/**
	 * Sets the id_perfil of this implicado.
	 *
	 * @param id_perfil the id_perfil of this implicado
	 */
	public void setId_perfil(int id_perfil);

	/**
	 * Returns the id_ciudad of this implicado.
	 *
	 * @return the id_ciudad of this implicado
	 */
	public Integer getId_ciudad();

	/**
	 * Sets the id_ciudad of this implicado.
	 *
	 * @param id_ciudad the id_ciudad of this implicado
	 */
	public void setId_ciudad(Integer id_ciudad);

	/**
	 * Returns the cod_entidad of this implicado.
	 *
	 * @return the cod_entidad of this implicado
	 */
	@AutoEscape
	public String getCod_entidad();

	/**
	 * Sets the cod_entidad of this implicado.
	 *
	 * @param cod_entidad the cod_entidad of this implicado
	 */
	public void setCod_entidad(String cod_entidad);

	/**
	 * Returns the cod_especialidad of this implicado.
	 *
	 * @return the cod_especialidad of this implicado
	 */
	@AutoEscape
	public String getCod_especialidad();

	/**
	 * Sets the cod_especialidad of this implicado.
	 *
	 * @param cod_especialidad the cod_especialidad of this implicado
	 */
	public void setCod_especialidad(String cod_especialidad);

	/**
	 * Returns the id_delegado of this implicado.
	 *
	 * @return the id_delegado of this implicado
	 */
	public Integer getId_delegado();

	/**
	 * Sets the id_delegado of this implicado.
	 *
	 * @param id_delegado the id_delegado of this implicado
	 */
	public void setId_delegado(Integer id_delegado);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Implicado implicado);

	public int hashCode();

	public CacheModel<Implicado> toCacheModel();

	public Implicado toEscapedModel();

	public String toString();

	public String toXmlString();
}