/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Parametros service. Represents a row in the &quot;SOLISALAD_PARAMETROS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.ParametrosModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.ParametrosImpl}.
 * </p>
 *
 * @author smontanez
 * @see Parametros
 * @see la.netco.solicitudes_sdisc.model.model.impl.ParametrosImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.ParametrosModelImpl
 * @generated
 */
public interface ParametrosModel extends BaseModel<Parametros> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parametros model instance should use the {@link Parametros} interface instead.
	 */

	/**
	 * Returns the primary key of this parametros.
	 *
	 * @return the primary key of this parametros
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this parametros.
	 *
	 * @param primaryKey the primary key of this parametros
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the tiempo_proximo_caducar of this parametros.
	 *
	 * @return the tiempo_proximo_caducar of this parametros
	 */
	public int getTiempo_proximo_caducar();

	/**
	 * Sets the tiempo_proximo_caducar of this parametros.
	 *
	 * @param tiempo_proximo_caducar the tiempo_proximo_caducar of this parametros
	 */
	public void setTiempo_proximo_caducar(int tiempo_proximo_caducar);

	/**
	 * Returns the tiempo_caducidad of this parametros.
	 *
	 * @return the tiempo_caducidad of this parametros
	 */
	public int getTiempo_caducidad();

	/**
	 * Sets the tiempo_caducidad of this parametros.
	 *
	 * @param tiempo_caducidad the tiempo_caducidad of this parametros
	 */
	public void setTiempo_caducidad(int tiempo_caducidad);

	/**
	 * Returns the email_resposable of this parametros.
	 *
	 * @return the email_resposable of this parametros
	 */
	@AutoEscape
	public String getEmail_resposable();

	/**
	 * Sets the email_resposable of this parametros.
	 *
	 * @param email_resposable the email_resposable of this parametros
	 */
	public void setEmail_resposable(String email_resposable);

	/**
	 * Returns the mensaje_email of this parametros.
	 *
	 * @return the mensaje_email of this parametros
	 */
	@AutoEscape
	public String getMensaje_email();

	/**
	 * Sets the mensaje_email of this parametros.
	 *
	 * @param mensaje_email the mensaje_email of this parametros
	 */
	public void setMensaje_email(String mensaje_email);

	/**
	 * Returns the asunto_email of this parametros.
	 *
	 * @return the asunto_email of this parametros
	 */
	@AutoEscape
	public String getAsunto_email();

	/**
	 * Sets the asunto_email of this parametros.
	 *
	 * @param asunto_email the asunto_email of this parametros
	 */
	public void setAsunto_email(String asunto_email);

	/**
	 * Returns the ID of this parametros.
	 *
	 * @return the ID of this parametros
	 */
	public int getId();

	/**
	 * Sets the ID of this parametros.
	 *
	 * @param id the ID of this parametros
	 */
	public void setId(int id);

	/**
	 * Returns the repository ID of this parametros.
	 *
	 * @return the repository ID of this parametros
	 */
	public long getRepositoryId();

	/**
	 * Sets the repository ID of this parametros.
	 *
	 * @param repositoryId the repository ID of this parametros
	 */
	public void setRepositoryId(long repositoryId);

	/**
	 * Returns the folder ID of this parametros.
	 *
	 * @return the folder ID of this parametros
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this parametros.
	 *
	 * @param folderId the folder ID of this parametros
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the user repository ID of this parametros.
	 *
	 * @return the user repository ID of this parametros
	 */
	public long getUserRepositoryId();

	/**
	 * Sets the user repository ID of this parametros.
	 *
	 * @param userRepositoryId the user repository ID of this parametros
	 */
	public void setUserRepositoryId(long userRepositoryId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Parametros parametros);

	public int hashCode();

	public CacheModel<Parametros> toCacheModel();

	public Parametros toEscapedModel();

	public String toString();

	public String toXmlString();
}