/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Solicitud service. Represents a row in the &quot;SOLISALAD_SOLICITUD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.SolicitudModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.SolicitudImpl}.
 * </p>
 *
 * @author smontanez
 * @see Solicitud
 * @see la.netco.solicitudes_sdisc.model.model.impl.SolicitudImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.SolicitudModelImpl
 * @generated
 */
public interface SolicitudModel extends BaseModel<Solicitud> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Solicitud model instance should use the {@link Solicitud} interface instead.
	 */

	/**
	 * Returns the primary key of this Solicitud.
	 *
	 * @return the primary key of this Solicitud
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this Solicitud.
	 *
	 * @param primaryKey the primary key of this Solicitud
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id_solicitud of this Solicitud.
	 *
	 * @return the id_solicitud of this Solicitud
	 */
	public int getId_solicitud();

	/**
	 * Sets the id_solicitud of this Solicitud.
	 *
	 * @param id_solicitud the id_solicitud of this Solicitud
	 */
	public void setId_solicitud(int id_solicitud);

	/**
	 * Returns the hechos of this Solicitud.
	 *
	 * @return the hechos of this Solicitud
	 */
	@AutoEscape
	public String getHechos();

	/**
	 * Sets the hechos of this Solicitud.
	 *
	 * @param hechos the hechos of this Solicitud
	 */
	public void setHechos(String hechos);

	/**
	 * Returns the pruebas of this Solicitud.
	 *
	 * @return the pruebas of this Solicitud
	 */
	@AutoEscape
	public String getPruebas();

	/**
	 * Sets the pruebas of this Solicitud.
	 *
	 * @param pruebas the pruebas of this Solicitud
	 */
	public void setPruebas(String pruebas);

	/**
	 * Returns the id_estado of this Solicitud.
	 *
	 * @return the id_estado of this Solicitud
	 */
	public int getId_estado();

	/**
	 * Sets the id_estado of this Solicitud.
	 *
	 * @param id_estado the id_estado of this Solicitud
	 */
	public void setId_estado(int id_estado);

	/**
	 * Returns the id_implicado of this Solicitud.
	 *
	 * @return the id_implicado of this Solicitud
	 */
	public int getId_implicado();

	/**
	 * Sets the id_implicado of this Solicitud.
	 *
	 * @param id_implicado the id_implicado of this Solicitud
	 */
	public void setId_implicado(int id_implicado);

	/**
	 * Returns the id_solicitante of this Solicitud.
	 *
	 * @return the id_solicitante of this Solicitud
	 */
	public int getId_solicitante();

	/**
	 * Sets the id_solicitante of this Solicitud.
	 *
	 * @param id_solicitante the id_solicitante of this Solicitud
	 */
	public void setId_solicitante(int id_solicitante);

	/**
	 * Returns the fecha registro of this Solicitud.
	 *
	 * @return the fecha registro of this Solicitud
	 */
	public Date getFechaRegistro();

	/**
	 * Sets the fecha registro of this Solicitud.
	 *
	 * @param fechaRegistro the fecha registro of this Solicitud
	 */
	public void setFechaRegistro(Date fechaRegistro);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Solicitud solicitud);

	public int hashCode();

	public CacheModel<Solicitud> toCacheModel();

	public Solicitud toEscapedModel();

	public String toString();

	public String toXmlString();
}