/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Solicitante service. Represents a row in the &quot;SOLISALAD_SOLICITANTE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.SolicitanteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.SolicitanteImpl}.
 * </p>
 *
 * @author smontanez
 * @see Solicitante
 * @see la.netco.solicitudes_sdisc.model.model.impl.SolicitanteImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.SolicitanteModelImpl
 * @generated
 */
public interface SolicitanteModel extends BaseModel<Solicitante> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a solicitante model instance should use the {@link Solicitante} interface instead.
	 */

	/**
	 * Returns the primary key of this solicitante.
	 *
	 * @return the primary key of this solicitante
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this solicitante.
	 *
	 * @param primaryKey the primary key of this solicitante
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id_solicitante of this solicitante.
	 *
	 * @return the id_solicitante of this solicitante
	 */
	public int getId_solicitante();

	/**
	 * Sets the id_solicitante of this solicitante.
	 *
	 * @param id_solicitante the id_solicitante of this solicitante
	 */
	public void setId_solicitante(int id_solicitante);

	/**
	 * Returns the nombres of this solicitante.
	 *
	 * @return the nombres of this solicitante
	 */
	@AutoEscape
	public String getNombres();

	/**
	 * Sets the nombres of this solicitante.
	 *
	 * @param nombres the nombres of this solicitante
	 */
	public void setNombres(String nombres);

	/**
	 * Returns the apellidos of this solicitante.
	 *
	 * @return the apellidos of this solicitante
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this solicitante.
	 *
	 * @param apellidos the apellidos of this solicitante
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the num_documento of this solicitante.
	 *
	 * @return the num_documento of this solicitante
	 */
	@AutoEscape
	public String getNum_documento();

	/**
	 * Sets the num_documento of this solicitante.
	 *
	 * @param num_documento the num_documento of this solicitante
	 */
	public void setNum_documento(String num_documento);

	/**
	 * Returns the telefono of this solicitante.
	 *
	 * @return the telefono of this solicitante
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this solicitante.
	 *
	 * @param telefono the telefono of this solicitante
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the email of this solicitante.
	 *
	 * @return the email of this solicitante
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this solicitante.
	 *
	 * @param email the email of this solicitante
	 */
	public void setEmail(String email);

	/**
	 * Returns the direccion of this solicitante.
	 *
	 * @return the direccion of this solicitante
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this solicitante.
	 *
	 * @param direccion the direccion of this solicitante
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the id_tipo_doc of this solicitante.
	 *
	 * @return the id_tipo_doc of this solicitante
	 */
	public Integer getId_tipo_doc();

	/**
	 * Sets the id_tipo_doc of this solicitante.
	 *
	 * @param id_tipo_doc the id_tipo_doc of this solicitante
	 */
	public void setId_tipo_doc(Integer id_tipo_doc);

	/**
	 * Returns the id_ciudad of this solicitante.
	 *
	 * @return the id_ciudad of this solicitante
	 */
	public Integer getId_ciudad();

	/**
	 * Sets the id_ciudad of this solicitante.
	 *
	 * @param id_ciudad the id_ciudad of this solicitante
	 */
	public void setId_ciudad(Integer id_ciudad);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Solicitante solicitante);

	public int hashCode();

	public CacheModel<Solicitante> toCacheModel();

	public Solicitante toEscapedModel();

	public String toString();

	public String toXmlString();
}