/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package la.netco.solicitudes_sdisc.model.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TipoDocumento service. Represents a row in the &quot;SOLISALAD_TIPO_DOCUMENTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link la.netco.solicitudes_sdisc.model.model.impl.TipoDocumentoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link la.netco.solicitudes_sdisc.model.model.impl.TipoDocumentoImpl}.
 * </p>
 *
 * @author smontanez
 * @see TipoDocumento
 * @see la.netco.solicitudes_sdisc.model.model.impl.TipoDocumentoImpl
 * @see la.netco.solicitudes_sdisc.model.model.impl.TipoDocumentoModelImpl
 * @generated
 */
public interface TipoDocumentoModel extends BaseModel<TipoDocumento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo documento model instance should use the {@link TipoDocumento} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo documento.
	 *
	 * @return the primary key of this tipo documento
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this tipo documento.
	 *
	 * @param primaryKey the primary key of this tipo documento
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the id_tipo_doc of this tipo documento.
	 *
	 * @return the id_tipo_doc of this tipo documento
	 */
	public int getId_tipo_doc();

	/**
	 * Sets the id_tipo_doc of this tipo documento.
	 *
	 * @param id_tipo_doc the id_tipo_doc of this tipo documento
	 */
	public void setId_tipo_doc(int id_tipo_doc);

	/**
	 * Returns the nombre of this tipo documento.
	 *
	 * @return the nombre of this tipo documento
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this tipo documento.
	 *
	 * @param nombre the nombre of this tipo documento
	 */
	public void setNombre(String nombre);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TipoDocumento tipoDocumento);

	public int hashCode();

	public CacheModel<TipoDocumento> toCacheModel();

	public TipoDocumento toEscapedModel();

	public String toString();

	public String toXmlString();
}